#!/usr/bin/env bash

readonly DAEMON_OPTS="
 -u memcached
 -p 11211
 -m ${MEMCACHED_CACHESIZE:-64}
 -c ${MEMCACHED_MAXCONN:-1024}
 ${MEMCACHED_OPTIONS:-}
"
readonly MEMCACHED=/usr/bin/memcached
readonly NICE=/bin/nice
readonly NICENESS=${MEMCACHED_NICENESS:-0}

printf -- \
	"Starting Memcached: %s" \
	"${DAEMON_OPTS}"

exec ${NICE} \
	-n ${NICENESS} \
	${MEMCACHED} \
	${DAEMON_OPTS}
